[versions]
kotlin = "1.9.25"
springBoot = "3.4.6"
springDependencyManagement = "1.1.7"
mybatisSpringBootStarter = "3.0.4"
sqlite = "3.49.1.0"

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "springBoot" }
springDependencyManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinPluginSpring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }

[libraries]
mybatisSpringBootStarter = { module = "org.mybatis.spring.boot:mybatis-spring-boot-starter", version.ref = "mybatisSpringBootStarter" }
mybatisSpringBootStarterTest = { module = "org.mybatis.spring.boot:mybatis-spring-boot-starter-test", version.ref = "mybatisSpringBootStarter" }
sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
