[versions]
kotlin = "2.2.21"
springBoot = "4.0.1"
springDependencyManagement = "1.1.7"
mybatisSpringBootStarter = "4.0.1"
sqlite = "3.51.1.0"
kotlinResult = "2.1.0"
kotest = "6.0.7"
kotlinLogging = "7.0.13"
commonsValidator = "1.10.1"
ulid = "8.3.0"

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "springBoot" }
springDependencyManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinPluginSpring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }

[libraries]
mybatisSpringBootStarter = { module = "org.mybatis.spring.boot:mybatis-spring-boot-starter", version.ref = "mybatisSpringBootStarter" }
mybatisSpringBootStarterTest = { module = "org.mybatis.spring.boot:mybatis-spring-boot-starter-test", version.ref = "mybatisSpringBootStarter" }
sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
kotlinResult = { module = "com.michael-bull.kotlin-result:kotlin-result", version.ref = "kotlinResult" }
kotest = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotlinLogging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlinLogging" }
commonsValidator = { module = "commons-validator:commons-validator", version.ref = "commonsValidator" }
ulid = { module = "de.huxhorn.sulky:de.huxhorn.sulky.ulid", version.ref = "ulid" }
